package com.eventdrivencommerce.order.infrastructure.messaging;
import com.eventdrivencommerce.order.api.OrderStatusStream;import com.eventdrivencommerce.order.application.exception.OrderNotFoundException;import com.eventdrivencommerce.order.application.port.out.*;import com.eventdrivencommerce.order.domain.model.Order;import com.fasterxml.jackson.databind.*;import org.springframework.kafka.annotation.KafkaListener;import org.springframework.stereotype.Component;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.UUID;
@Component public class SagaEventConsumer {
 static final String GROUP="order-service-v1";private final ObjectMapper mapper;private final OrderRepository orders;private final ProcessedEventRepository processed;private final OrderEventOutbox outbox;private final Clock clock;private final OrderStatusStream stream;
 public SagaEventConsumer(ObjectMapper mapper,OrderRepository orders,ProcessedEventRepository processed,OrderEventOutbox outbox,Clock clock,OrderStatusStream stream){this.mapper=mapper;this.orders=orders;this.processed=processed;this.outbox=outbox;this.clock=clock;this.stream=stream;}
 @KafkaListener(topics={"commerce.inventory.v1","commerce.payment.v1","commerce.delivery.v1"},groupId=GROUP) @Transactional public void consume(String json)throws Exception{
  JsonNode event=mapper.readTree(json),payload=event.path("payload");UUID eventId=uuid(event,"eventId"),orderId=payload.hasNonNull("orderId")?UUID.fromString(payload.get("orderId").asText()):uuid(event,"aggregateId");String type=event.path("eventType").asText();var key=new ProcessedEventId(GROUP,eventId);if(processed.existsById(key))return;Order order=orders.findById(orderId).orElseThrow(()->new OrderNotFoundException(orderId));Instant now=clock.instant();
  switch(type){case "InventoryReservedV1"->order.inventoryReserved(now);case "InventoryReservationFailedV1"->order.inventoryReservationFailed(payload.path("reasonCode").asText("INVENTORY_UNAVAILABLE"),now);case "PaymentCompletedV1"->order.paymentCompleted(now);case "PaymentFailedV1"->order.paymentFailed(now);case "InventoryReleasedV1"->order.inventoryReleased(now);case "DeliveryCreatedV1"->order.deliveryCreated(now);case "DeliveryFailedV1"->order.deliveryFailed(now);case "DeliveryStatusChangedV1"->{if("DELIVERED".equals(payload.path("status").asText()))order.delivered(now);else return;}case "RefundCompletedV1","PaymentRefundedV1"->order.refundCompleted(now);default->{return;}}
  Order saved=orders.save(order);UUID correlation=event.hasNonNull("correlationId")?uuid(event,"correlationId"):UUID.randomUUID();if(saved.status()==com.eventdrivencommerce.order.domain.model.OrderStatus.COMPLETED)outbox.orderCompleted(saved,correlation,eventId,now);if(saved.status()==com.eventdrivencommerce.order.domain.model.OrderStatus.CANCELLED)outbox.orderCancelled(saved,correlation,eventId,now);processed.save(new ProcessedEventJpaEntity(key,type,now));stream.publish(saved);
 }
 private static UUID uuid(JsonNode node,String field){return UUID.fromString(node.path(field).asText());}
}
