package com.eventdrivencommerce.order.infrastructure.outbox;
import com.eventdrivencommerce.order.application.port.out.OrderEventOutbox;import com.eventdrivencommerce.order.domain.model.Order;import com.fasterxml.jackson.databind.ObjectMapper;import com.fasterxml.jackson.databind.node.ObjectNode;import org.springframework.stereotype.Component;import java.time.Instant;import java.util.UUID;
@Component class JpaOrderEventOutbox implements OrderEventOutbox {
 private final SpringDataOutboxRepository repository;private final ObjectMapper mapper;JpaOrderEventOutbox(SpringDataOutboxRepository repository,ObjectMapper mapper){this.repository=repository;this.mapper=mapper;}
 public void orderCreated(Order o,UUID correlation,UUID causation,Instant now){ObjectNode payload=mapper.createObjectNode();payload.put("orderId",o.id().toString()).put("customerId",o.customerId().toString()).put("totalAmount",o.totalAmount()).put("currency",o.currency());payload.set("lines",mapper.valueToTree(o.lines()));payload.set("shippingAddress",mapper.valueToTree(o.shippingAddress()));append("OrderCreatedV1",o,correlation,causation,now,payload);}
 public void orderCompleted(Order o,UUID correlation,UUID causation,Instant now){ObjectNode payload=mapper.createObjectNode().put("orderId",o.id().toString()).put("customerId",o.customerId().toString()).put("completedAt",now.toString());append("OrderCompletedV1",o,correlation,causation,now,payload);}
 public void orderCancelled(Order o,UUID correlation,UUID causation,Instant now){ObjectNode payload=mapper.createObjectNode().put("orderId",o.id().toString()).put("customerId",o.customerId().toString()).put("reasonCode",o.cancellationReason()).put("cancelledAt",now.toString());append("OrderCancelledV1",o,correlation,causation,now,payload);}
 private void append(String type,Order o,UUID correlation,UUID causation,Instant now,ObjectNode body){UUID id=UUID.randomUUID();ObjectNode envelope=mapper.createObjectNode();envelope.put("eventId",id.toString()).put("eventType",type).put("eventVersion",1).put("aggregateId",o.id().toString()).put("correlationId",correlation.toString()).put("causationId",causation.toString()).put("occurredAt",now.toString()).set("payload",body);repository.save(OutboxJpaEntity.pending(id,o.id(),type,correlation,causation,now,envelope));}
}
