package com.eventdrivencommerce.order.infrastructure.outbox;
import org.apache.kafka.clients.producer.ProducerRecord;import org.springframework.beans.factory.annotation.Value;import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;import org.springframework.kafka.core.KafkaTemplate;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Component;import org.springframework.transaction.annotation.Transactional;import java.nio.charset.StandardCharsets;import java.time.*;import java.util.concurrent.TimeUnit;
@Component @ConditionalOnProperty(name="order.outbox.publisher-enabled",havingValue="true",matchIfMissing=true)
public class OutboxPublisher {
 private final SpringDataOutboxRepository repository;private final KafkaTemplate<String,String> kafka;private final Clock clock;private final String topic;private final int batchSize;private final Duration timeout;
 public OutboxPublisher(SpringDataOutboxRepository repository,KafkaTemplate<String,String> kafka,Clock clock,@Value("${order.outbox.topic}")String topic,@Value("${order.outbox.batch-size:50}")int batchSize,@Value("${order.outbox.publish-timeout:PT10S}")Duration timeout){this.repository=repository;this.kafka=kafka;this.clock=clock;this.topic=topic;this.batchSize=batchSize;this.timeout=timeout;}
 @Scheduled(fixedDelayString="${order.outbox.poll-interval:PT1S}") @Transactional public void publishPending(){for(var event:repository.lockPending(batchSize)){try{var record=new ProducerRecord<String,String>(topic,event.aggregateId.toString(),event.payload.toString());header(record,"eventId",event.eventId.toString());header(record,"eventType",event.eventType);header(record,"eventVersion","1");header(record,"correlationId",event.correlationId.toString());header(record,"causationId",event.causationId.toString());header(record,"contentType","application/json");header(record,"schema",schema(event.eventType));header(record,"producer","order-service");kafka.send(record).get(timeout.toMillis(),TimeUnit.MILLISECONDS);event.published(clock.instant());}catch(Exception ex){event.failed(clock.instant(),root(ex));}}}
 private static String schema(String type){return switch(type){case "OrderCreatedV1"->"order-created-v1.schema.json";case "OrderCompletedV1"->"order-completed-v1.schema.json";default->"order-cancelled-v1.schema.json";};}private static void header(ProducerRecord<String,String>r,String n,String v){r.headers().add(n,v.getBytes(StandardCharsets.UTF_8));}private static String root(Exception e){Throwable t=e;while(t.getCause()!=null)t=t.getCause();return t.getMessage();}
}
