package com.eventdrivencommerce.payment.infrastructure.outbox;
import com.eventdrivencommerce.payment.application.port.PaymentEventOutbox;import com.eventdrivencommerce.payment.domain.Payment;import com.fasterxml.jackson.databind.*;import com.fasterxml.jackson.databind.node.ObjectNode;import org.springframework.stereotype.Component;import java.time.Instant;import java.util.UUID;
@Component class JpaPaymentEventOutbox implements PaymentEventOutbox{
 private final SpringDataOutboxRepository repository;private final ObjectMapper mapper;JpaPaymentEventOutbox(SpringDataOutboxRepository repository,ObjectMapper mapper){this.repository=repository;this.mapper=mapper;}
 public void paymentCompleted(Payment p,UUID c,UUID cause,Instant now){var body=money(p).put("providerReference",p.providerReference()).put("completedAt",now.toString());append("PaymentCompletedV1",p,c,cause,now,body);}
 public void paymentFailed(Payment p,boolean retryable,UUID c,UUID cause,Instant now){var body=money(p).put("reasonCode",p.failureReason()).put("retryable",retryable).put("failedAt",now.toString());append("PaymentFailedV1",p,c,cause,now,body);}
 public void refundRequested(Payment p,String reason,UUID c,UUID cause,Instant now){var body=refundMoney(p).put("reasonCode",reason).put("requestedAt",now.toString());append("RefundRequestedV1",p,c,cause,now,body);}
 public void refundCompleted(Payment p,UUID c,UUID cause,Instant now){var body=refundMoney(p).put("providerReference",p.refundProviderReference()).put("completedAt",now.toString());append("RefundCompletedV1",p,c,cause,now,body);}
 public void refundFailed(Payment p,boolean retryable,UUID c,UUID cause,Instant now){var body=mapper.createObjectNode().put("refundId",p.refundId().toString()).put("paymentId",p.id().toString()).put("orderId",p.orderId().toString()).put("reasonCode",p.failureReason()).put("retryable",retryable).put("failedAt",now.toString());append("RefundFailedV1",p,c,cause,now,body);}
 private ObjectNode money(Payment p){return mapper.createObjectNode().put("paymentId",p.id().toString()).put("orderId",p.orderId().toString()).put("amount",p.amount()).put("currency",p.currency());}private ObjectNode refundMoney(Payment p){return money(p).put("refundId",p.refundId().toString());}
 private void append(String type,Payment p,UUID c,UUID cause,Instant now,ObjectNode body){UUID id=UUID.randomUUID();var envelope=mapper.createObjectNode();envelope.put("eventId",id.toString()).put("eventType",type).put("eventVersion",1).put("aggregateId",p.id().toString()).put("correlationId",c.toString()).put("causationId",cause.toString()).put("occurredAt",now.toString()).set("payload",body);repository.save(OutboxJpaEntity.pending(id,p.id(),type,c,cause,now,envelope));}
}
