package com.eventdrivencommerce.order.api;
import com.eventdrivencommerce.order.application.exception.*;import com.eventdrivencommerce.order.domain.exception.InvalidOrderTransitionException;import io.github.resilience4j.circuitbreaker.CallNotPermittedException;import jakarta.servlet.http.HttpServletRequest;import org.springframework.http.*;import org.springframework.web.bind.MethodArgumentNotValidException;import org.springframework.web.bind.annotation.*;import org.springframework.web.method.annotation.HandlerMethodValidationException;import java.net.URI;
@RestControllerAdvice public class ApiExceptionHandler {
    @ExceptionHandler(OrderNotFoundException.class) ResponseEntity<ProblemDetail> notFound(RuntimeException ex,HttpServletRequest req){return problem(HttpStatus.NOT_FOUND,"Order not found",ex,req);}
    @ExceptionHandler(IdempotencyConflictException.class) ResponseEntity<ProblemDetail> conflict(RuntimeException ex,HttpServletRequest req){return problem(HttpStatus.CONFLICT,"Idempotency conflict",ex,req);}
    @ExceptionHandler({ProductValidationException.class,InvalidOrderTransitionException.class}) ResponseEntity<ProblemDetail> unprocessable(RuntimeException ex,HttpServletRequest req){return problem(HttpStatus.UNPROCESSABLE_ENTITY,"Order cannot be processed",ex,req);}
    @ExceptionHandler(CallNotPermittedException.class) ResponseEntity<ProblemDetail> unavailable(RuntimeException ex,HttpServletRequest req){return problem(HttpStatus.SERVICE_UNAVAILABLE,"Product service unavailable",ex,req);}
    @ExceptionHandler({MethodArgumentNotValidException.class,HandlerMethodValidationException.class,IllegalArgumentException.class}) ResponseEntity<ProblemDetail> badRequest(Exception ex,HttpServletRequest req){return problem(HttpStatus.BAD_REQUEST,"Invalid request",ex,req);}
    private ResponseEntity<ProblemDetail> problem(HttpStatus status,String title,Exception ex,HttpServletRequest req){var p=ProblemDetail.forStatusAndDetail(status,ex.getMessage());p.setTitle(title);p.setType(URI.create("https://api.event-driven-commerce.local/problems/"+title.toLowerCase().replace(' ','-')));p.setInstance(URI.create(req.getRequestURI()));p.setProperty("correlationId",req.getAttribute(CorrelationIdFilter.HEADER));return ResponseEntity.status(status).contentType(MediaType.APPLICATION_PROBLEM_JSON).body(p);}
}
