package com.eventdrivencommerce.order.application.service;
import com.eventdrivencommerce.order.application.exception.IdempotencyConflictException;import com.eventdrivencommerce.order.application.model.*;import com.eventdrivencommerce.order.application.port.out.*;import com.eventdrivencommerce.order.domain.model.*;import org.junit.jupiter.api.Test;import java.math.BigDecimal;import java.time.*;import java.util.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;
class OrderApplicationServiceTest {
 OrderRepository repository=mock(OrderRepository.class);ProductCatalog products=mock(ProductCatalog.class);OrderEventOutbox outbox=mock(OrderEventOutbox.class);Clock clock=Clock.fixed(Instant.parse("2026-01-01T00:00:00Z"),ZoneOffset.UTC);OrderApplicationService service=new OrderApplicationService(repository,products,outbox,clock);
 @Test void validatesPricesPersistsAndAppendsCreatedEvent(){UUID productId=UUID.randomUUID();when(repository.findByCustomerAndIdempotencyKey(any(),any())).thenReturn(Optional.empty());when(products.get(productId)).thenReturn(new ProductSnapshot(productId,"SKU","Product",new BigDecimal("12.50"),"SEK",true));when(repository.save(any())).thenAnswer(i->i.getArgument(0));var result=service.create(command(productId,"key","fp"));assertThat(result.replayed()).isFalse();assertThat(result.order().totalAmount()).isEqualByComparingTo("25.00");verify(outbox).orderCreated(eq(result.order()),any(),any(),eq(clock.instant()));}
 @Test void replaysSameRequestWithoutDuplicatingEvent(){UUID p=UUID.randomUUID();var existing=existing(p,"fp");when(repository.findByCustomerAndIdempotencyKey(existing.customerId(),"key")).thenReturn(Optional.of(existing));var result=service.create(command(existing.customerId(),p,"key","fp"));assertThat(result.replayed()).isTrue();verifyNoInteractions(products,outbox);}
 @Test void rejectsKeyReuseWithDifferentPayload(){UUID p=UUID.randomUUID();var existing=existing(p,"old");when(repository.findByCustomerAndIdempotencyKey(existing.customerId(),"key")).thenReturn(Optional.of(existing));assertThatThrownBy(()->service.create(command(existing.customerId(),p,"key","new"))).isInstanceOf(IdempotencyConflictException.class);}
 private CreateOrderCommand command(UUID p,String key,String fp){return command(UUID.randomUUID(),p,key,fp);}private CreateOrderCommand command(UUID customer,UUID p,String key,String fp){var a=new Address("Name","Street","","123","City","SE");return new CreateOrderCommand(customer,List.of(new CreateOrderCommand.RequestedLine(p,2)),"SEK",a,a,key,fp,UUID.randomUUID());}private Order existing(UUID p,String fp){var a=new Address("Name","Street","","123","City","SE");return Order.create(UUID.randomUUID(),List.of(OrderLine.priced(p,"SKU","Product",1,BigDecimal.ONE)),"SEK",a,a,"key",fp,clock.instant());}
}
